controller_manager:
  ros__parameters:
    update_rate: 100 # Joint state pub rate
    diagnostics:
      threshold:
        controller_manager:
          periodicity:
            mean_error:
              warn: 1.0
              error: 10.0
            standard_deviation:
              warn: 1.0
              error: 10.0
        controllers:
          execution_time:
            mean_error:
              warn: 10.0
              error: 2000.0
            standard_deviation:
              warn: 10.0
              error: 200.0
          periodicity:
            mean_error:
              warn: 1.0
              error: 10.0
            standard_deviation:
              warn: 1.0
              error: 10.0
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dg5f_right_controller:
      type: joint_trajectory_controller/JointTrajectoryController

dg5f_right_controller:
  ros__parameters:
    state_publish_rate: 500.0 # 50Hz에서 500Hz로 변경
    action_monitor_rate: 500.0 # 20Hz에서 500Hz로 변경
    gains:
      rj_dg_1_1:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_1_2:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_1_3:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_1_4:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_2_1:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_2_2:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_2_3:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_2_4:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_3_1:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_3_2:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_3_3:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_3_4:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_4_1:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_4_2:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_4_3:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_4_4:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_5_1:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_5_2:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_5_3:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0
      rj_dg_5_4:
        p: 150.0
        i: 3.0
        d: 5.0
        i_clamp: 10.0

    allow_partial_joints_goal: True
    joints:
      - rj_dg_1_1
      - rj_dg_1_2
      - rj_dg_1_3
      - rj_dg_1_4
      - rj_dg_2_1
      - rj_dg_2_2
      - rj_dg_2_3
      - rj_dg_2_4
      - rj_dg_3_1
      - rj_dg_3_2
      - rj_dg_3_3
      - rj_dg_3_4
      - rj_dg_4_1
      - rj_dg_4_2
      - rj_dg_4_3
      - rj_dg_4_4
      - rj_dg_5_1
      - rj_dg_5_2
      - rj_dg_5_3
      - rj_dg_5_4

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    update_rate: 200 # Joint state pub rate
    joints:
      - rj_dg_1_1
      - rj_dg_1_2
      - rj_dg_1_3
      - rj_dg_1_4
      - rj_dg_2_1
      - rj_dg_2_2
      - rj_dg_2_3
      - rj_dg_2_4
      - rj_dg_3_1
      - rj_dg_3_2
      - rj_dg_3_3
      - rj_dg_3_4
      - rj_dg_4_1
      - rj_dg_4_2
      - rj_dg_4_3
      - rj_dg_4_4
      - rj_dg_5_1
      - rj_dg_5_2
      - rj_dg_5_3
      - rj_dg_5_4
