services:
  ros-core:
    # TODO: Change the image based on your platform.
    image: osrf/ros:noetic-desktop-full
    # image: arm64v8/ros:noetic
    container_name: ros-core
    command: "rosmaster --core"
    network_mode: host
    env_file: .env
    healthcheck:
      # The healthcheck is required for ros1-bridge to wait until roscore is ready.
      test: /ros_entrypoint.sh bash -c "rostopic list || exit 1"
      interval: 3s
      timeout: 10s
      retries: 5
  ros1-bridge:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
      # TODO: Specify the target platform to build the image, otherwise it will build for the host platform.
      # Reference: https://docs.docker.com/compose/compose-file/build/#platforms
      # platforms:
      #   - "linux/arm64"
      # TODO: Set Isaac Sim version or set to "" if not using Isaac Sim
      # args:
      #   ISAAC_SIM_VERSION: "4.5.0"
    image: j3soon/ros2-ros1-bridge-ws
    container_name: ros2-ros1-bridge-ws
    depends_on:
      ros-core:
        # The healthcheck is required for ros1-bridge to wait until roscore is ready.
        condition: service_healthy
    command: ./start-bridge.sh $ROS_MASTER_URI
    stdin_open: true
    tty: true
    network_mode: host
    working_dir: /
    env_file: .env
    volumes:
      # Mount local timezone into container.
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount Direct Rendering Infrastructure (DRI) for hardware acceleration support such as OpenGL.
      - /dev/dri:/dev/dri
      # Mount shared memory for ROS2 communication.
      - /dev/shm:/dev/shm
  ros1:
    # TODO: Change the image based on your platform.
    image: osrf/ros:noetic-desktop-full
    # image: arm64v8/ros:noetic
    container_name: ros1
    stdin_open: true
    tty: true
    network_mode: host
    env_file: .env
    depends_on:
      ros-core:
        condition: service_healthy
  ros2:
    # TODO: Change the image based on your platform.
    image: osrf/ros:humble-desktop-full
    # image: arm64v8/ros:humble
    container_name: ros2
    stdin_open: true
    tty: true
    network_mode: host
    env_file: .env
    volumes:
      # Mount shared memory for ROS2 communication.
      - /dev/shm:/dev/shm
