
name: ROS 2 CI

on:
  push:
    branches: [ humble,  humble-dev ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ humble, humble-dev ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        env:
          ROS_DISTRO: humble
        run: |
          sudo apt update
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y

      - name: Build with colcon
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+
