name: Build Docker Image for cartographer-ws

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/build-cartographer-ws.yaml
      - cartographer_ws/docker/Dockerfile
      - cartographer_ws/docker/.dockerignore
      - cartographer_ws/docker/.bashrc

jobs:
  docker:
    if: github.repository == 'j3soon/ros2-agv-essentials'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        # Ref: https://github.com/docker/metadata-action
        uses: docker/metadata-action@v5
        with:
          # Link: https://hub.docker.com/repository/docker/j3soon/ros2-cartographer-ws/tags
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ros2-cartographer-ws
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: cartographer_ws/docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
