name: Build Docker Image for template-ws

on:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - v*

jobs:
  paths-filter:
    if: github.repository == 'j3soon/ros2-essentials'
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.filter.outputs.results }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          results:
            - .github/workflows/build-template-ws.yaml
            - template_ws/docker/Dockerfile
            - template_ws/docker/.dockerignore
            - template_ws/docker/.bashrc
    - name: Changes matched
      if: steps.filter.outputs.results == 'true'
      run: echo "Changes matched, will build image"
    - name: Changes didn't match
      if: steps.filter.outputs.results != 'true'
      run: echo "Changes didn't match, will NOT build image"
    # Ref: https://github.com/dorny/paths-filter/issues/147#issuecomment-1287800590
    - name: Save base ref info
      run: |
        BASE=${{ github.event.before }}
        CURRENT_BRANCH=${{ github.ref }}
        echo $BASE > base.txt
        echo $CURRENT_BRANCH > current-branch.txt
    - name: Upload base ref info
      uses: actions/upload-artifact@v4
      with:
        name: original-refs
        path: |
          base.txt
          current-branch.txt
        retention-days: 1
  docker:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.results == 'true' || startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /var/lib/docker/
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Restart docker
        run: sudo service docker restart
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - # Ref: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token
        name: Prepare tag name as environment variable
        run: |
          # This strips the git ref prefix from the version.
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # This strips the "v" prefix from the tag name.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # This uses the Docker `latest` tag convention.
          [ "$VERSION" == "main" ] && VERSION=latest
          # Output the environment variable
          # Ref: https://stackoverflow.com/a/57989070
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          # Print for debugging purpose
          echo "VERSION=$VERSION"
      - name: Docker meta
        id: meta
        # Ref: https://github.com/docker/metadata-action
        uses: docker/metadata-action@v5
        with:
          # Link: https://hub.docker.com/repository/docker/j3soon/ros2-template-ws/tags
          images: j3soon/ros2-template-ws
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=${{ env.VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: j3soon
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: template_ws/docker
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
      # Ref: https://github.com/docker/buildx/discussions/1382#discussioncomment-6252049
      - name: Push amd64 cache
        uses: docker/build-push-action@v6
        with:
          context: template_ws/docker
          cache-to: type=registry,ref=j3soon/ros2-template-ws:buildcache-amd64,mode=max
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
      - name: Push arm64 cache
        uses: docker/build-push-action@v6
        with:
          context: template_ws/docker
          cache-to: type=registry,ref=j3soon/ros2-template-ws:buildcache-arm64,mode=max
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: template_ws/docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
