name: Build Docker Image for template-ws

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/build-template-ws.yaml
      - template_ws/Dockerfile

jobs:
  docker:
    if: github.repository == 'j3soon/ros2-agv-essentials'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        # Ref: https://github.com/docker/metadata-action
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ros2-template-ws
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD'}}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: template_ws/docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
